###
POST http://localhost:5000/auth/signup
content-type: application/json
Accept: application/json

{
    "email": "dan@test.com",
    "username": "Danny",
    "password": "Thisisgood1",
    "firstName": "Daniel",
    "lastName": "Murphy"
}

###
POST http://localhost:5000/auth/signin
content-type: application/json
Accept: application/json

{
    "username": "dan@test.com",
    "password": "Thisisgood1"
}

###
POST http://localhost:5000/auth/signout
content-type: application/json
Accept: application/json

{}